version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/app 
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command:  "yarn run dev"
    ports:
      - "3000:3000"