version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app 
    command:  npm run dev"
    ports:
      - "3000:3000"